### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by bonniepeters** [bonniepeters/dailies-django#1]
## Setup 

- [x] Create a directory ```dailies-django```

- [x] ```cd``` into ```dailies-django```

- [x] Install Django: ```pipenv install django```

- [x] Install library to connect Django to WeekgreSQL: ```pipenv install psycopg2-binary```

- [x] Open ```dailies-django```: ```code .```

- [x] Start Django project: ```pipenv run django-admin startproject dailies-project .```

- [x] Activate virtual environment: ```pipenv shell```

- [x] Create app: ```django-admin startapp dailies``` 

## Database Connection

- [x] Login to psql: ```psql -d Postgres```

- [x] Create a database:
```
> CREATE DATABASE dailiesdb;
> CREATE USER myUser WITH PASSWORD 'user';
> GRANT ALL PRIVILEGES ON DATABASE dailiesdb TO myuser;
> \q
```

- [x] Add Database details:
```python
# dailies-project/settings.py
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends..Postgresql',
    'NAME': 'dailiesdb',
    'USER': 'myuser',
    'PASSWORD': 'user',
    'HOST': 'localhost'
   }
}
```

- [x] Add ```dailies``` to installed apps:
```python
# dailies-project/settings.py
INSTALLED_APPS = [
  'dailies'
]
```

- [x] Start server: ```python3 manage.py runserver```

- [x] Navigate to ```localhost:8000```. (You should see a page welcoming you to Django!)

## Models

- [x] Create models in ```dailies/models.py```:

```python
class Week(models.Model):
    number = models.PositiveIntegerField(default=1)
    startDate = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.number} - {self.startDate}"

class Day(models.Model):
    DAYS = (
        ('MON', 'MON'),
        ('TUE', 'TUE'),
        ('WED', 'WED'),
        ('THU', 'THU'),
        ('FRI', 'FRI'),
        ('SAT', 'SAT'),
        ('SUN', 'SUN'),
    )
    week = models.ForeignKey(Week, on_delete=models.CASCADE, related_name='days')
    caption = models.CharField(max_length=400, default='')
    number = models.PositiveIntegerField(default=1000)
    day = models.CharField(max_length=3, choices=DAYS, default='SUN')
    water = models.BooleanField(default=False)
    work = models.BooleanField(default=False)
    connect = models.BooleanField(default=False)
    workout = models.BooleanField(default=False)
    music = models.BooleanField(default=False)
    code = models.BooleanField(default=False)
    mindful = models.BooleanField(default=False)
    read = models.BooleanField(default=False)
    learn = models.BooleanField(default=False)
    vitamins = models.BooleanField(default=False)
    timeSlots = models.PositiveIntegerField(default=0)
    outside = models.BooleanField(default=False)
    earth = models.BooleanField(default=False)
    food = models.BooleanField(default=False)
    oils = models.BooleanField(default=False)
    weight = models.DecimalField(default=145, max_digits=4, decimal_places=1)
    awake = models.TimeField(default='04:00', auto_now=False, auto_now_add=False)
    asleep = models.TimeField(default='21:00', auto_now=False, auto_now_add=False)

    def __str__(self):
        return f"{self.week.number} - {self.number} - {self.caption}"
```

## Migrations

- [x] Stage migration to the database: ```python3 manage.py makemigrations```

NOTE: Every time you make changes to your models, run ```makemigrations``` again.

- [x] Migrate staged changes: ```python3 manage.py migrate```

## Admin Console

- [x] Create a super user: ```python3 manage.py createsuperuser```

- [x] Fill in the info in the boxes that pop up.

- [x] Import models in ```dailies/admin.py```:

```python
from django.contrib import admin
from .models import Week, Day

admin.site.register(Week, Day)
```

## Django REST Framework

- [x] Install the `djangorestframework`: pipenv install djangorestframework

- [x] Add ```'rest_framework',``` to your `INSTALLED_APPS` list in `settings.py` 

- [x] Add this variable as a new dictionary, anywhere in `settings.py`:

```python
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
```

- [x] In the `urls` list in `dailies-project/urls.py`, add the following to
`urlpatterns`:

```python
path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
```

## Serializers

Note: the `HyperlinkedModelSerializer` allows you to link from one model to another.

- [x] Create a new file in `dailies` called `serializers.py`:

```python
from rest_framework import serializers
from .models import Week, Day

class DaySerializer(serializers.ModelSerializer):
    class Meta:
        model = Day
        fields = (week, caption, number, day, water, work, connect, workout, music, code, mindful, read, learn, vitamins, timeSlots, outside, earth, food, oils, weight, awake, asleep,)

class WeekSerializer(serializers.ModelSerializer):
    days = DaySerializer(
        many=True,
        read_only=True
    )

    class Meta:
        model = Week
        fields = ('numbers', 'startDate', 'days',)
```

## Views

```py
from rest_framework import generics
from .serializers import WeekSerializer, DaySerializer
from .models import Week, Day

class WeekList(generics.ListCreateAPIView):
    queryset = Week.objects.all()
    serializer_class = WeekSerializer

class WeekCreate(generics.CreateAPIView):
    queryset = Week.objects.all()
    serializer_class = WeekSerializer

class WeekDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Week.objects.all()
    serializer_class = WeekSerializer

class DayList(generics.ListCreateAPIView):
    queryset = Day.objects.all()
    serializer_class = DaySerializer

class DayCreate(generics.CreateAPIView):
    queryset = Day.objects.all()
    serializer_class = DaySerializer

class DayDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Day.objects.all()
    serializer_class = DaySerializer
```
## URLs

```py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

urlpatterns = [
    path('weeks', views.WeekList.as_view(), name='week_list'),
    path('week/add', views.WeekCreate.as_view(), name='week_create'),
    path('day/add', views.DayCreate.as_view(), name='day_create'),
    path('weeks/<int:pk>', views.WeekDetail.as_view(), name='week_detail'),
    path('days', views.DayList.as_view(), name='day_list'),
    path('days/<int:pk>', views.DayDetail.as_view(), name='day_detail'),
]
```

## Adding Fields with URLs to Detail Views

```diff
class WeekSerializer(serializers.HyperlinkedModelSerializer):
    comments = serializers.HyperlinkedRelatedField(
        view_name='comment_detail',
        many=True,
        read_only=True,
    )

+    Week_url = serializers.ModelSerializer.serializer_url_field(
+        view_name='Week_detail'
+    )

    class Meta:
        model = Week
-        fields = ('id', 'photo_url', 'nationality', 'name', 'songs',)
+        fields = ('id', 'artist_url', 'photo_url', 'nationality', 'name', 'songs',)
```
